In [60]:
import numpy as np

# creating matrix using numpy

In [90]:
matrix_0 = np.matrix([2,2], dtype=int)
print(type(matrix_0))
print(matrix_0)

<class 'numpy.matrix'>
[[2 2]]


In [83]:
matrix_1 = np.array([[3,3,3],[4,5,5]])
print(matrix_1)

[[3 3 3]
 [4 5 5]]


In [62]:
matrix_1.shape

(2, 3)

In [63]:
matrix_1.size

6

In [64]:
matrix_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# creating matrices with random values

In [65]:
matrix_3 = np.random.rand(3,3)*10
print(matrix_3)

[[7.19348576 1.72434809 8.75800963]
 [0.90531985 5.7633127  4.89834758]
 [0.6960554  0.90821871 9.6497719 ]]


In [66]:
matrix_4 = np.random.randint(1,15,size=(3,3))
print(matrix_4)

[[ 8  3 12]
 [ 2  3  6]
 [ 8 13 13]]


In [67]:
matrix_5 = np.ones((2,2), dtype = int)
print(matrix_5)

[[1 1]
 [1 1]]


## null or zero matrix

In [68]:
matrix_6 = np.zeros(shape=(2,2), dtype = int)
print(matrix_6)

[[0 0]
 [0 0]]


## identity matrix

In [69]:
matrix_7 = np.identity(2) # or np.eye()
print(matrix_7)

[[1. 0.]
 [0. 1.]]


## transpose of a matrix

In [70]:
matrix_8 = np.random.rand(3,3)*10
print(matrix_8)

[[6.81346461 6.37501313 6.61705825]
 [5.39588543 0.93154055 2.8237368 ]
 [6.75723136 2.47492321 7.42663747]]


In [71]:
transpose_8 = np.transpose(matrix_8)
print(transpose_8)

[[6.81346461 5.39588543 6.75723136]
 [6.37501313 0.93154055 2.47492321]
 [6.61705825 2.8237368  7.42663747]]


## matrix addition, substraction and multiplication

In [72]:
print(matrix_1)
print(matrix_1+matrix_1)
print(matrix_1-matrix_1)

[[3 3 3]
 [4 5 5]]
[[ 6  6  6]
 [ 8 10 10]]
[[0 0 0]
 [0 0 0]]


In [112]:
np.random.seed(1)

In [113]:
m_1 = np.random.randint(1,10,size=(2,3))
m_2 = np.random.randint(1,10,size=(3,2))
m_3 = np.dot(m_1,m_2)
print(type(m_1), '\n',m_1)
print(type(m_2), '\n',m_2)
print(type(m_3), '\n',m_3)

<class 'numpy.ndarray'> 
 [[6 9 6]
 [1 1 2]]
<class 'numpy.ndarray'> 
 [[8 7]
 [3 5]
 [6 3]]
<class 'numpy.ndarray'> 
 [[111 105]
 [ 23  18]]


In [114]:
from numpy import matrix


m_1 = matrix(m_1)
m_2 = matrix(m_2)
m_3 = m_1*m_2
print(type(m_1), '\n',m_1)
print(type(m_2), '\n',m_2)
print(type(m_3), '\n',m_3)

<class 'numpy.matrix'> 
 [[6 9 6]
 [1 1 2]]
<class 'numpy.matrix'> 
 [[8 7]
 [3 5]
 [6 3]]
<class 'numpy.matrix'> 
 [[111 105]
 [ 23  18]]


**element wise multiplication**

In [119]:
m_1 = np.random.randint(1,10,size=(3,3))
m_2 = np.random.randint(1,10,size=(3,3))
m_3 = m_1*m_2 # or np.multiply(m_1, m_2)
print(type(m_1), '\n',m_1)
print(type(m_2), '\n',m_2)
print(type(m_3), '\n',m_3)

<class 'numpy.ndarray'> 
 [[8 8 8]
 [4 1 9]
 [8 8 2]]
<class 'numpy.ndarray'> 
 [[2 4 1]
 [9 7 5]
 [6 7 3]]
<class 'numpy.ndarray'> 
 [[16 32  8]
 [36  7 45]
 [48 56  6]]
